#!/bin/bash

# this is a script for testing the api endpoints by sending JSON data.  It may only consist of a line or two, but I want it to be callable without a lot of typing so there we are.  Also doesn't hurt to practice shell scripts.

echo 'testing JSON...'

echo '{"email":"bob@bob.com","name":"bob","password":"password"}'

curl -d '{"email":"bob@bob.com","name":"bob","password":"password"}' -H "Content-Type: application/json" -X POST http://localhost:8080/api/v1/user
